### ISSUE TITLE
Fails when Key is just a String

### ISSUE THREAD

**Issue by ee07dazn** [EladLeev/KeyToField-smt#19]
Hello

Thanks for writing this SMT out. Much appreciated 🙇‍♂️ 

Currently, I believe it works only when key is a struct object. 
Is it possible to make it work when key is just a string.
In my case, I simply need to add the key as part of the value with a defined attribute name.

Let me know if this is possible. 

I am non-java coder otherwise instead of raising an issue, I would have raised a PR for review.

**Comment by EladLeev** [comment]
Thanks for the feedback @ee07dazn!
It's indeed possible, and I should have cover it as part of the tests.
I'll try to get to it asap

**Comment by EladLeev** [comment]
Hey @ee07dazn - There's a new release which fix the bug.
Thanks for reporting!

**Comment by ee07dazn** [comment]
Thanks @EladLeev - Much appreciated!! I am just gonna pull the latest and test it out now.

**Comment by ee07dazn** [comment]
Worked like a charm! 🙇‍♂️ 🚀
